ALTER TABLE village_ethnicities
ADD COLUMN  date_upload DATETIME DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE village_answer_question
ADD COLUMN  date_upload DATETIME DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE village_ground_categories
ADD COLUMN  date_upload DATETIME DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE village_images
ADD COLUMN  date_upload DATETIME DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE village_living_conditions
ADD COLUMN  date_upload DATETIME DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE village_objects
ADD COLUMN  date_upload DATETIME DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE village_population_assertion
ADD COLUMN  date_upload DATETIME DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE populations
ADD COLUMN  date_upload DATETIME DEFAULT CURRENT_TIMESTAMP;