name: build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: set up java
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'oracle'
          cache: maven

      - name: mvn clean install
        run: mvn clean install